CREATE TABLE xbox_achievement_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_entry_id bigint NOT NULL REFERENCES user_game_library(id) ON DELETE CASCADE,
    name varchar(200) NOT NULL,
    group_type varchar(20) NOT NULL CHECK (group_type IN ('BASE_GAME', 'DLC')),
    total_achievements integer NOT NULL DEFAULT 0 CHECK (total_achievements >= 0),
    unlocked_achievements integer NOT NULL DEFAULT 0 CHECK (unlocked_achievements >= 0),
    total_gamerscore integer NOT NULL DEFAULT 0 CHECK (total_gamerscore >= 0),
    earned_gamerscore integer NOT NULL DEFAULT 0 CHECK (earned_gamerscore >= 0),
    CHECK (unlocked_achievements <= total_achievements),
    CHECK (earned_gamerscore <= total_gamerscore),
    UNIQUE (library_entry_id, name)
);

CREATE UNIQUE INDEX ux_xbox_achievement_groups_base
    ON xbox_achievement_groups(library_entry_id) WHERE group_type = 'BASE_GAME';

INSERT INTO xbox_achievement_groups (library_entry_id, name, group_type, total_achievements,
        unlocked_achievements, total_gamerscore, earned_gamerscore)
SELECT library_entry_id, 'Основная игра', 'BASE_GAME', total_achievements,
       unlocked_achievements, total_gamerscore, earned_gamerscore
FROM xbox_game_progress;

ALTER TABLE game_sessions ADD COLUMN achievement_group_id bigint;

UPDATE game_sessions session
SET achievement_group_id = achievement_group.id
FROM xbox_achievement_groups achievement_group
WHERE achievement_group.library_entry_id = session.library_entry_id
  AND achievement_group.group_type = 'BASE_GAME'
  AND (session.unlocked_achievements > 0 OR session.earned_gamerscore > 0);

ALTER TABLE game_sessions
    ADD CONSTRAINT fk_game_sessions_achievement_group
    FOREIGN KEY (achievement_group_id) REFERENCES xbox_achievement_groups(id) ON DELETE SET NULL;

CREATE INDEX idx_game_sessions_achievement_group_id ON game_sessions(achievement_group_id);
