ALTER TABLE content_items DROP CONSTRAINT content_items_item_type_check;
ALTER TABLE content_items DROP CONSTRAINT content_items_check;

ALTER TABLE content_items ADD CONSTRAINT content_items_item_type_check
    CHECK (item_type IN ('MOVIE', 'SERIES', 'ANIME', 'GAME', 'BOOK'));
ALTER TABLE content_items ADD CONSTRAINT content_items_format_by_type_check CHECK (
    (item_type IN ('MOVIE', 'SERIES') AND format IN ('LIVE_ACTION', 'ANIMATION')) OR
    (item_type = 'ANIME' AND format = 'ANIME') OR
    (item_type IN ('GAME', 'BOOK') AND format IS NULL)
);

CREATE TABLE books (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id bigint NOT NULL UNIQUE REFERENCES content_items(id) ON DELETE CASCADE,
    author varchar(300) NOT NULL,
    book_format varchar(20) NOT NULL CHECK (book_format IN ('PAPER', 'EBOOK', 'AUDIOBOOK')),
    page_count integer CHECK (page_count > 0)
);

CREATE TABLE book_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_content_id bigint NOT NULL UNIQUE REFERENCES user_content(id) ON DELETE CASCADE,
    current_page integer NOT NULL DEFAULT 0 CHECK (current_page >= 0),
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reading_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_content_id bigint NOT NULL REFERENCES user_content(id) ON DELETE CASCADE,
    started_at timestamptz NOT NULL,
    duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
    pages_read integer NOT NULL DEFAULT 0 CHECK (pages_read >= 0),
    note text
);

CREATE INDEX idx_reading_sessions_user_content_started
    ON reading_sessions(user_content_id, started_at DESC);
