ALTER TABLE episode_watch_history
    ADD COLUMN is_bulk boolean NOT NULL DEFAULT false;

CREATE TABLE season_completion_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    season_id bigint NOT NULL REFERENCES content_seasons(id) ON DELETE CASCADE,
    completed_at timestamptz,
    episode_count integer NOT NULL CHECK (episode_count > 0),
    UNIQUE (user_id, season_id)
);

CREATE INDEX idx_season_completion_history_season_id
    ON season_completion_history(season_id);
