CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(100) NOT NULL UNIQUE,
    display_name varchar(200),
    email varchar(320) UNIQUE,
    timezone varchar(100) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE daily_activity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    activity_date date NOT NULL,
    steps bigint CHECK (steps >= 0),
    distance_meters bigint CHECK (distance_meters >= 0),
    note text,
    UNIQUE (user_id, activity_date)
);

CREATE TABLE sleep_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    started_at timestamptz NOT NULL,
    ended_at timestamptz NOT NULL,
    deep_sleep_minutes integer CHECK (deep_sleep_minutes >= 0),
    light_sleep_minutes integer CHECK (light_sleep_minutes >= 0),
    rem_sleep_minutes integer CHECK (rem_sleep_minutes >= 0),
    awake_minutes integer CHECK (awake_minutes >= 0),
    quality_rating smallint CHECK (quality_rating BETWEEN 1 AND 5),
    note text,
    CHECK (ended_at > started_at)
);

CREATE TABLE content_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(300) NOT NULL,
    original_title varchar(300),
    item_type varchar(20) NOT NULL CHECK (item_type IN ('MOVIE', 'SERIES', 'ANIME', 'GAME')),
    format varchar(20) CHECK (format IN ('LIVE_ACTION', 'ANIMATION', 'ANIME')),
    release_year integer CHECK (release_year > 0),
    description text,
    cover_url text,
    duration_minutes integer CHECK (duration_minutes > 0),
    CHECK (
        (item_type = 'MOVIE' AND format IN ('LIVE_ACTION', 'ANIMATION')) OR
        (item_type = 'SERIES' AND format IN ('LIVE_ACTION', 'ANIMATION')) OR
        (item_type = 'ANIME' AND format = 'ANIME') OR
        (item_type = 'GAME' AND format IS NULL)
    )
);

CREATE TABLE content_seasons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id bigint NOT NULL REFERENCES content_items(id) ON DELETE CASCADE,
    season_number integer NOT NULL CHECK (season_number > 0),
    title varchar(300),
    release_year integer CHECK (release_year > 0),
    UNIQUE (content_id, season_number)
);

CREATE TABLE content_episodes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id bigint NOT NULL REFERENCES content_seasons(id) ON DELETE CASCADE,
    episode_number integer NOT NULL CHECK (episode_number > 0),
    title varchar(300) NOT NULL,
    duration_minutes integer CHECK (duration_minutes > 0),
    release_date date,
    UNIQUE (season_id, episode_number)
);

CREATE TABLE user_content (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content_id bigint NOT NULL REFERENCES content_items(id) ON DELETE CASCADE,
    status varchar(20) NOT NULL CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'PAUSED', 'DROPPED')),
    rating smallint CHECK (rating BETWEEN 1 AND 10),
    is_favorite boolean NOT NULL DEFAULT false,
    started_at timestamptz,
    completed_at timestamptz,
    personal_note text,
    UNIQUE (user_id, content_id),
    CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE episode_watch_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    episode_id bigint NOT NULL REFERENCES content_episodes(id) ON DELETE CASCADE,
    watched_at timestamptz NOT NULL,
    watch_number integer NOT NULL CHECK (watch_number > 0),
    UNIQUE (user_id, episode_id, watch_number)
);

CREATE TABLE movie_watch_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content_id bigint NOT NULL REFERENCES content_items(id) ON DELETE CASCADE,
    watched_at timestamptz NOT NULL,
    watch_number integer NOT NULL CHECK (watch_number > 0),
    UNIQUE (user_id, content_id, watch_number)
);

CREATE TABLE gaming_platforms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE game_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(100) NOT NULL UNIQUE,
    source_type varchar(20) NOT NULL CHECK (source_type IN ('DIGITAL_STORE', 'PHYSICAL', 'SUBSCRIPTION'))
);

CREATE TABLE user_game_library (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_content_id bigint NOT NULL REFERENCES user_content(id) ON DELETE CASCADE,
    platform_id bigint NOT NULL REFERENCES gaming_platforms(id),
    source_id bigint NOT NULL REFERENCES game_sources(id),
    access_type varchar(20) NOT NULL CHECK (access_type IN ('OWNED', 'SUBSCRIPTION')),
    edition varchar(200),
    acquired_at timestamptz,
    note text
);

CREATE TABLE xbox_game_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_entry_id bigint NOT NULL UNIQUE REFERENCES user_game_library(id) ON DELETE CASCADE,
    total_achievements integer NOT NULL DEFAULT 0 CHECK (total_achievements >= 0),
    unlocked_achievements integer NOT NULL DEFAULT 0 CHECK (unlocked_achievements >= 0),
    total_gamerscore integer NOT NULL DEFAULT 0 CHECK (total_gamerscore >= 0),
    earned_gamerscore integer NOT NULL DEFAULT 0 CHECK (earned_gamerscore >= 0),
    last_updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (unlocked_achievements <= total_achievements),
    CHECK (earned_gamerscore <= total_gamerscore)
);

CREATE TABLE habits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name varchar(200) NOT NULL,
    description text,
    tracking_type varchar(20) NOT NULL CHECK (tracking_type IN ('BOOLEAN', 'NUMBER', 'DURATION')),
    data_source varchar(40) NOT NULL CHECK (data_source IN ('MANUAL', 'DAILY_ACTIVITY_STEPS', 'DAILY_ACTIVITY_DISTANCE', 'SLEEP_DURATION')),
    target_value numeric(14, 2) CHECK (target_value >= 0),
    unit varchar(50),
    schedule_type varchar(20) NOT NULL CHECK (schedule_type IN ('DAILY', 'SELECTED_DAYS')),
    start_date date NOT NULL,
    end_date date,
    status varchar(20) NOT NULL CHECK (status IN ('ACTIVE', 'PAUSED', 'ARCHIVED')),
    CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE habit_schedule_days (
    habit_id bigint NOT NULL REFERENCES habits(id) ON DELETE CASCADE,
    day_of_week smallint NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    PRIMARY KEY (habit_id, day_of_week)
);

CREATE TABLE habit_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habit_id bigint NOT NULL REFERENCES habits(id) ON DELETE CASCADE,
    entry_date date NOT NULL,
    value numeric(14, 2),
    target_value_snapshot numeric(14, 2) CHECK (target_value_snapshot >= 0),
    is_skipped boolean NOT NULL DEFAULT false,
    note text,
    recorded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (habit_id, entry_date)
);

CREATE TABLE journal_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    entry_date date NOT NULL,
    title varchar(300),
    content text NOT NULL,
    is_pinned boolean NOT NULL DEFAULT false
);

CREATE TABLE blog_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source_journal_entry_id bigint REFERENCES journal_entries(id) ON DELETE SET NULL,
    title varchar(300) NOT NULL,
    slug varchar(300) NOT NULL,
    excerpt text,
    content text NOT NULL,
    cover_image_url text,
    status varchar(20) NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    published_at timestamptz,
    UNIQUE (user_id, slug)
);

CREATE TABLE tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name varchar(100) NOT NULL,
    slug varchar(100) NOT NULL,
    UNIQUE (user_id, slug)
);

CREATE TABLE journal_entry_tags (
    journal_entry_id bigint NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (journal_entry_id, tag_id)
);

CREATE TABLE blog_post_tags (
    blog_post_id bigint NOT NULL REFERENCES blog_posts(id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (blog_post_id, tag_id)
);

CREATE TABLE calendar_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title varchar(300) NOT NULL,
    description text,
    event_type varchar(20) NOT NULL CHECK (event_type IN ('EVENT', 'TASK', 'REMINDER')),
    schedule_type varchar(20) NOT NULL CHECK (schedule_type IN ('ONCE', 'DAILY', 'WEEKLY', 'SELECTED_DAYS')),
    start_date date NOT NULL,
    repeat_until date,
    start_time time,
    end_time time,
    is_all_day boolean NOT NULL DEFAULT false,
    location varchar(500),
    status varchar(20) NOT NULL CHECK (status IN ('ACTIVE', 'PAUSED', 'ARCHIVED')),
    CHECK (repeat_until IS NULL OR repeat_until >= start_date),
    CHECK (end_time IS NULL OR start_time IS NULL OR end_time > start_time),
    CHECK (NOT is_all_day OR (start_time IS NULL AND end_time IS NULL))
);

CREATE TABLE calendar_event_schedule_days (
    event_id bigint NOT NULL REFERENCES calendar_events(id) ON DELETE CASCADE,
    day_of_week smallint NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    PRIMARY KEY (event_id, day_of_week)
);

CREATE TABLE calendar_event_occurrences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES calendar_events(id) ON DELETE CASCADE,
    occurrence_date date NOT NULL,
    status varchar(20) NOT NULL CHECK (status IN ('COMPLETED', 'CANCELLED', 'SKIPPED')),
    completed_at timestamptz,
    note text,
    UNIQUE (event_id, occurrence_date)
);

CREATE INDEX idx_daily_activity_activity_date ON daily_activity(activity_date);
CREATE INDEX idx_sleep_sessions_user_id ON sleep_sessions(user_id);
CREATE INDEX idx_sleep_sessions_ended_at ON sleep_sessions(ended_at);
CREATE INDEX idx_content_items_item_type ON content_items(item_type);
CREATE INDEX idx_user_content_content_id ON user_content(content_id);
CREATE INDEX idx_user_content_status ON user_content(status);
CREATE INDEX idx_episode_watch_history_episode_id ON episode_watch_history(episode_id);
CREATE INDEX idx_episode_watch_history_watched_at ON episode_watch_history(watched_at);
CREATE INDEX idx_movie_watch_history_content_id ON movie_watch_history(content_id);
CREATE INDEX idx_movie_watch_history_watched_at ON movie_watch_history(watched_at);
CREATE INDEX idx_user_game_library_user_content_id ON user_game_library(user_content_id);
CREATE INDEX idx_user_game_library_platform_id ON user_game_library(platform_id);
CREATE INDEX idx_user_game_library_source_id ON user_game_library(source_id);
CREATE INDEX idx_habits_user_id ON habits(user_id);
CREATE INDEX idx_habit_entries_entry_date ON habit_entries(entry_date);
CREATE INDEX idx_journal_entries_user_id ON journal_entries(user_id);
CREATE INDEX idx_journal_entries_entry_date ON journal_entries(entry_date);
CREATE INDEX idx_blog_posts_source_journal_entry_id ON blog_posts(source_journal_entry_id);
CREATE INDEX idx_blog_posts_status ON blog_posts(status);
CREATE INDEX idx_blog_posts_published_at ON blog_posts(published_at);
CREATE INDEX idx_tags_user_id ON tags(user_id);
CREATE INDEX idx_journal_entry_tags_tag_id ON journal_entry_tags(tag_id);
CREATE INDEX idx_blog_post_tags_tag_id ON blog_post_tags(tag_id);
CREATE INDEX idx_calendar_events_user_id ON calendar_events(user_id);
CREATE INDEX idx_calendar_events_start_date ON calendar_events(start_date);
CREATE INDEX idx_calendar_event_occurrences_occurrence_date ON calendar_event_occurrences(occurrence_date);
