CREATE TABLE steam_game_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_entry_id bigint NOT NULL UNIQUE REFERENCES user_game_library(id) ON DELETE CASCADE,
    total_achievements integer NOT NULL DEFAULT 0 CHECK (total_achievements >= 0),
    unlocked_achievements integer NOT NULL DEFAULT 0 CHECK (unlocked_achievements >= 0),
    last_unlocked_at timestamptz,
    last_synced_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (unlocked_achievements <= total_achievements)
);

CREATE TABLE steam_achievements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    progress_id bigint NOT NULL REFERENCES steam_game_progress(id) ON DELETE CASCADE,
    api_name varchar(255) NOT NULL,
    display_name varchar(500) NOT NULL,
    description text,
    icon_url text,
    locked_icon_url text,
    is_hidden boolean NOT NULL DEFAULT false,
    is_unlocked boolean NOT NULL DEFAULT false,
    unlocked_at timestamptz,
    UNIQUE (progress_id, api_name)
);

CREATE INDEX idx_steam_achievements_progress_id ON steam_achievements(progress_id);
CREATE INDEX idx_steam_achievements_unlocked_at ON steam_achievements(unlocked_at DESC);
