CREATE TABLE xbox_achievements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    progress_id bigint NOT NULL REFERENCES xbox_game_progress(id) ON DELETE CASCADE,
    achievement_id varchar(255) NOT NULL,
    display_name varchar(500) NOT NULL,
    description text,
    locked_description text,
    icon_url text,
    gamerscore integer NOT NULL DEFAULT 0 CHECK (gamerscore >= 0),
    is_hidden boolean NOT NULL DEFAULT false,
    is_unlocked boolean NOT NULL DEFAULT false,
    unlocked_at timestamptz,
    UNIQUE (progress_id, achievement_id)
);

CREATE INDEX idx_xbox_achievements_progress_id ON xbox_achievements(progress_id);
CREATE INDEX idx_xbox_achievements_unlocked_at ON xbox_achievements(unlocked_at DESC);
