CREATE TABLE game_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_entry_id bigint NOT NULL REFERENCES user_game_library(id) ON DELETE CASCADE,
    started_at timestamptz NOT NULL,
    duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
    note text
);

CREATE INDEX idx_game_sessions_library_entry_id ON game_sessions(library_entry_id);
CREATE INDEX idx_game_sessions_started_at ON game_sessions(started_at);
