ALTER TABLE content_items
    ADD COLUMN developer varchar(200),
    ADD COLUMN release_date date,
    ADD COLUMN xbox_play_anywhere boolean NOT NULL DEFAULT false;

CREATE TABLE game_playthroughs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_entry_id bigint NOT NULL REFERENCES user_game_library(id) ON DELETE CASCADE,
    playthrough_number integer NOT NULL CHECK (playthrough_number > 0),
    completed_at timestamptz NOT NULL,
    playtime_minutes bigint NOT NULL CHECK (playtime_minutes >= 0),
    note text,
    UNIQUE (library_entry_id, playthrough_number)
);

CREATE INDEX idx_game_playthroughs_library_entry_id ON game_playthroughs(library_entry_id);
