import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { createBook, createReadingSession, deleteBook, getBooks, putBookLibrary, putBookProgress, removeBookLibrary, updateBook, type Book, type BookFormat, type BookInput, type BookLibraryInput, type ReadingSessionInput } from '../api/books'
import type { LibraryStatus } from '../api/movies'

const statusLabels: Record<LibraryStatus,string>={NOT_STARTED:'Не начата',PLANNED:'В планах',IN_PROGRESS:'Читаю',COMPLETED:'Прочитана',PAUSED:'На паузе',DROPPED:'Брошена'}
const formatLabels:Record<BookFormat,string>={PAPER:'Бумажная',EBOOK:'Электронная',AUDIOBOOK:'Аудиокнига'}
const emptyBook:BookInput={title:'',author:'',bookFormat:'PAPER',pageCount:null,releaseYear:null,genre:null,coverUrl:null,description:null}
const localDateTime=(value:string)=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}

export function BooksPage(){
 const [books,setBooks]=useState<Book[]>([]);const [editing,setEditing]=useState<Book|'new'|null>(null);const [progressBook,setProgressBook]=useState<Book|null>(null);const [sessionBook,setSessionBook]=useState<Book|null>(null);const [query,setQuery]=useState('');const [status,setStatus]=useState<LibraryStatus|''>('');const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setBooks(await getBooks())}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось загрузить книги')}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 const visible=useMemo(()=>{const q=query.trim().toLocaleLowerCase('ru-RU');return books.filter(book=>(!q||`${book.title} ${book.author}`.toLocaleLowerCase('ru-RU').includes(q))&&(!status||book.status===status))},[books,query,status])
 return <div className="movies-page books-page"><section className="media-toolbar"><div className="journal-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти книгу или автора"/></div><div className="media-filters"><select value={status} onChange={e=>setStatus(e.target.value as LibraryStatus|'')}><option value="">Все статусы</option>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button className="primary-button" onClick={()=>setEditing('new')}>+ Добавить книгу</button></div></section>
 <section className="media-stats"><div><strong>{books.length}</strong><span>в каталоге</span></div><div><strong>{books.filter(b=>b.libraryEntryId).length}</strong><span>в библиотеке</span></div><div><strong>{books.filter(b=>b.status==='IN_PROGRESS').length}</strong><span>читаю</span></div><div><strong>{books.reduce((sum,b)=>sum+b.sessions.reduce((s,x)=>s+x.pagesRead,0),0)}</strong><span>страниц в сессиях</span></div></section>
 {error&&<div className="notice error movies-error"><strong>Ошибка</strong><span>{error}</span></div>}
 {loading?<div className="loading"><span/>Загружаем книги…</div>:visible.length===0?<div className="media-empty"><span>▥</span><h2>Книг пока нет</h2><p>Добавьте первую книгу в библиотеку.</p></div>:<section className="book-grid">{visible.map(book=><article className="book-card" key={book.id}><button className="book-cover" onClick={()=>setEditing(book)} style={book.coverUrl?{backgroundImage:`url(${book.coverUrl})`}:undefined}><span>{book.title.slice(0,1)}</span>{book.favorite&&<i>♥</i>}<em>{formatLabels[book.bookFormat]}</em></button><div className="book-card-info"><h3>{book.title}</h3><p>{book.author}</p><small>{book.releaseYear??'—'}{book.genre?` · ${book.genre}`:''}</small>{book.libraryEntryId&&book.pageCount&&<><div className="book-progress"><span style={{width:`${book.progressPercent}%`}}/></div><small>{book.currentPage??0} из {book.pageCount} стр. · {Math.round(book.progressPercent)}%</small></>} {book.status?<div className={`media-status ${book.status.toLowerCase()}`}>{statusLabels[book.status]}</div>:<button className="add-library-button" onClick={()=>setEditing(book)}>+ В библиотеку</button>}<div className="book-actions"><button disabled={!book.libraryEntryId||!book.pageCount} onClick={()=>setProgressBook(book)}>Страница</button><button disabled={!book.libraryEntryId} onClick={()=>setSessionBook(book)}>Сеанс</button><button onClick={()=>setEditing(book)}>Изменить</button></div></div></article>)}</section>}
 {editing&&<BookForm book={editing==='new'?undefined:editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);void load()}}/>}
 {progressBook&&<ProgressForm book={progressBook} onClose={()=>setProgressBook(null)} onSaved={()=>{setProgressBook(null);void load()}}/>}
 {sessionBook&&<SessionForm book={sessionBook} onClose={()=>setSessionBook(null)} onSaved={()=>{setSessionBook(null);void load()}}/>}
 </div>
}

function BookForm({book,onClose,onSaved}:{book?:Book;onClose:()=>void;onSaved:()=>void}){
 const [item,setItem]=useState<BookInput>(book?{title:book.title,author:book.author,bookFormat:book.bookFormat,pageCount:book.pageCount,releaseYear:book.releaseYear,genre:book.genre,coverUrl:book.coverUrl,description:book.description}:emptyBook)
 const [inLibrary,setInLibrary]=useState(Boolean(book?.libraryEntryId));const [library,setLibrary]=useState<BookLibraryInput>({status:book?.status??'NOT_STARTED',rating:book?.rating??null,favorite:book?.favorite??false,startedAt:book?.startedAt??null,completedAt:book?.completedAt??null,personalNote:book?.personalNote??null});const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null)
 const set=<K extends keyof BookInput>(key:K,value:BookInput[K])=>setItem(current=>({...current,[key]:value}));const setLib=<K extends keyof BookLibraryInput>(key:K,value:BookLibraryInput[K])=>setLibrary(current=>({...current,[key]:value}))
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError(null);try{const saved=book?await updateBook(book.id,item):await createBook(item);if(inLibrary)await putBookLibrary(saved.id,library);else if(book?.libraryEntryId)await removeBookLibrary(saved.id);onSaved()}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось сохранить книгу')}finally{setSaving(false)}}
 const remove=async()=>{if(!book||!confirm(`Удалить «${book.title}»?`))return;await deleteBook(book.id);onSaved()}
 return <div className="modal-backdrop"><form className="habit-form book-form" onSubmit={e=>void submit(e)}><div className="form-heading"><div><p className="eyebrow">Книги</p><h2>{book?'Редактирование':'Новая книга'}</h2></div><button type="button" onClick={onClose}>×</button></div>{error&&<div className="form-error">{error}</div>}<label>Название<input required maxLength={300} value={item.title} onChange={e=>set('title',e.target.value)}/></label><label>Автор<input required maxLength={300} value={item.author} onChange={e=>set('author',e.target.value)}/></label><div className="form-grid"><label>Формат<select value={item.bookFormat} onChange={e=>set('bookFormat',e.target.value as BookFormat)}>{Object.entries(formatLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Количество страниц<input min="1" type="number" value={item.pageCount??''} onChange={e=>set('pageCount',e.target.value?Number(e.target.value):null)}/></label><label>Год<input min="1" type="number" value={item.releaseYear??''} onChange={e=>set('releaseYear',e.target.value?Number(e.target.value):null)}/></label><label>Жанр<input maxLength={100} value={item.genre??''} onChange={e=>set('genre',e.target.value||null)}/></label></div><label>URL обложки<input type="url" value={item.coverUrl??''} onChange={e=>set('coverUrl',e.target.value||null)}/></label><label>Описание<textarea rows={3} value={item.description??''} onChange={e=>set('description',e.target.value||null)}/></label><fieldset className="library-fields"><legend>Моя библиотека</legend><label className="all-day-check"><input type="checkbox" checked={inLibrary} onChange={e=>setInLibrary(e.target.checked)}/>Добавить в библиотеку</label>{inLibrary&&<><div className="form-grid"><label>Статус<select value={library.status} onChange={e=>setLib('status',e.target.value as LibraryStatus)}>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Оценка<select value={library.rating??''} onChange={e=>setLib('rating',e.target.value?Number(e.target.value):null)}><option value="">Без оценки</option>{Array.from({length:10},(_,i)=>i+1).map(value=><option key={value}>{value}</option>)}</select></label></div><label className="favorite-check"><input type="checkbox" checked={library.favorite} onChange={e=>setLib('favorite',e.target.checked)}/>В избранном</label><label>Заметка<textarea rows={2} value={library.personalNote??''} onChange={e=>setLib('personalNote',e.target.value||null)}/></label></>}</fieldset><div className="form-buttons">{book&&<button className="danger-button" type="button" onClick={()=>void remove()}>Удалить</button>}<button className="secondary-button" type="button" onClick={onClose}>Отмена</button><button className="primary-button" disabled={saving}>{saving?'Сохраняем…':'Сохранить'}</button></div></form></div>
}

function ProgressForm({book,onClose,onSaved}:{book:Book;onClose:()=>void;onSaved:()=>void}){const [page,setPage]=useState(book.currentPage??0);const [error,setError]=useState<string|null>(null);const submit=async(e:FormEvent)=>{e.preventDefault();try{await putBookProgress(book.id,page);onSaved()}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось обновить прогресс')}};return <div className="modal-backdrop"><form className="habit-form compact-book-form" onSubmit={e=>void submit(e)}><div className="form-heading"><div><p className="eyebrow">Прогресс чтения</p><h2>{book.title}</h2></div><button type="button" onClick={onClose}>×</button></div>{error&&<div className="form-error">{error}</div>}<label>Текущая страница<input required min="0" max={book.pageCount??undefined} type="number" value={page} onChange={e=>setPage(Number(e.target.value))}/></label><div className="form-buttons"><button className="secondary-button" type="button" onClick={onClose}>Отмена</button><button className="primary-button">Сохранить</button></div></form></div>}

function SessionForm({book,onClose,onSaved}:{book:Book;onClose:()=>void;onSaved:()=>void}){const [input,setInput]=useState<ReadingSessionInput>({startedAt:new Date().toISOString(),durationMinutes:30,pagesRead:0,note:null});const [error,setError]=useState<string|null>(null);const submit=async(e:FormEvent)=>{e.preventDefault();try{await createReadingSession(book.id,input);onSaved()}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось сохранить сеанс')}};return <div className="modal-backdrop"><form className="habit-form compact-book-form" onSubmit={e=>void submit(e)}><div className="form-heading"><div><p className="eyebrow">Сеанс чтения</p><h2>{book.title}</h2></div><button type="button" onClick={onClose}>×</button></div>{error&&<div className="form-error">{error}</div>}<label>Начало<input type="datetime-local" value={localDateTime(input.startedAt)} onChange={e=>setInput(current=>({...current,startedAt:new Date(e.target.value).toISOString()}))}/></label><div className="form-grid"><label>Продолжительность, минут<input min="1" type="number" value={input.durationMinutes} onChange={e=>setInput(current=>({...current,durationMinutes:Number(e.target.value)}))}/></label><label>Прочитано страниц<input min="0" type="number" value={input.pagesRead} onChange={e=>setInput(current=>({...current,pagesRead:Number(e.target.value)}))}/></label></div><label>Заметка<textarea rows={3} value={input.note??''} onChange={e=>setInput(current=>({...current,note:e.target.value||null}))}/></label><div className="form-buttons"><button className="secondary-button" type="button" onClick={onClose}>Отмена</button><button className="primary-button">Сохранить</button></div></form></div>}
