import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router'
import { createMovie, deleteMovie, getMovieCatalog, putInLibrary, updateMovie, type ContentFormat, type LibraryEntry, type LibraryInput, type LibraryStatus, type Movie, type MovieInput } from '../api/movies'

const statusLabels: Record<LibraryStatus, string> = { NOT_STARTED: 'Не начато', PLANNED: 'В планах', IN_PROGRESS: 'Смотрю', COMPLETED: 'Просмотрено', PAUSED: 'На паузе', DROPPED: 'Брошено' }
const movieStatuses: LibraryStatus[] = ['PLANNED', 'COMPLETED']
const emptyMovie: MovieInput = { title: '', originalTitle: null, itemType: 'MOVIE', format: 'LIVE_ACTION', releaseYear: null, description: null, coverUrl: null, durationMinutes: null, releaseStatus: 'RELEASED', genre: null, developer: null, releaseDate: null, xboxPlayAnywhere: false }
const emptyLibrary: LibraryInput = { status: 'PLANNED', rating: null, favorite: false, startedAt: null, completedAt: null, personalNote: null }
const formatDuration = (minutes: number | null) => minutes == null ? null : `${Math.floor(minutes / 60)} ч ${minutes % 60} мин`

export function MoviesPage() {
  const navigate = useNavigate()
  const [movies, setMovies] = useState<Movie[]>([])
  const [library, setLibrary] = useState<Record<number, LibraryEntry>>({})
  const [editing, setEditing] = useState<Movie | 'new' | null>(null)
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState<LibraryStatus | ''>('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const load = useCallback(async () => { setLoading(true); setError(null); try { const catalog = await getMovieCatalog(); const items: Movie[] = catalog.map((item) => ({ ...item, itemType: 'MOVIE', xboxPlayAnywhere: false })); setMovies(items); setLibrary(Object.fromEntries(catalog.filter((item) => item.libraryId && item.userStatus).map((item) => [item.id, { id: item.libraryId!, content: { ...item, itemType: 'MOVIE', xboxPlayAnywhere: false }, status: item.userStatus!, rating: item.rating, favorite: item.favorite, startedAt: item.startedAt, completedAt: item.completedAt, personalNote: item.personalNote }] as const))) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось загрузить фильмы') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const visible = useMemo(() => { const normalized = query.trim().toLocaleLowerCase('ru-RU'); return movies.filter((movie) => (!normalized || `${movie.title} ${movie.originalTitle ?? ''}`.toLocaleLowerCase('ru-RU').includes(normalized)) && (!status || library[movie.id]?.status === status)) }, [library, movies, query, status])

  return <div className="movies-page series-page movie-catalog-page">
    <section className="media-toolbar series-media-toolbar"><div className="series-status-tabs movie-status-tabs" aria-label="Фильтр фильмов по статусу">{([['', 'Все'], ['PLANNED', 'В планах'], ['COMPLETED', 'Просмотрено']] as const).map(([value, label]) => <button key={value || 'all'} className={status === value ? 'active' : ''} onClick={() => setStatus(value)}>{label}</button>)}</div><div className="journal-search series-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Найти фильм" /></div><button className="primary-button series-add-button media-add-button" onClick={() => setEditing('new')}>+ Добавить фильм</button></section>
    <section className="series-catalog-layout"><div className="series-catalog-main">
    {error && <div className="notice error movies-error"><strong>Ошибка</strong><span>{error}</span></div>}
    {loading ? <div className="loading"><span />Загружаем медиатеку…</div> : visible.length === 0 ? <div className="media-empty"><span>▶</span><h2>Фильмов пока нет</h2><p>Добавьте первый фильм в каталог.</p></div> : <section className="movie-grid series-catalog-grid">{visible.map((movie) => { const entry = library[movie.id]; return <article className="series-list-card" key={movie.id}><button className="series-list-cover movie-list-cover" onClick={() => navigate(`/movies/${movie.id}`)} style={movie.coverUrl ? { backgroundImage: `url(${movie.coverUrl})` } : undefined}><span>{movie.title.slice(0, 1)}</span>{entry?.favorite && <i>♥</i>}</button><div className="series-list-content"><div className="series-list-heading"><button onClick={() => navigate(`/movies/${movie.id}`)}>{movie.title}</button><span className="release-badge released">{movie.format === 'ANIMATION' ? 'Мультфильм' : 'Фильм'}</span></div>{movie.originalTitle && <p>{movie.originalTitle}</p>}<div className="movie-list-meta"><span>{movie.releaseYear ?? '—'}</span>{movie.genre && <span>{movie.genre}</span>}{movie.durationMinutes && <span>{formatDuration(movie.durationMinutes)}</span>}</div><div className="series-list-inline-status">{entry ? <span className={`media-status ${entry.status.toLowerCase()}`}>{statusLabels[entry.status]}</span> : <span className="media-status not_started">Не в библиотеке</span>}</div></div><div className="series-list-side">{entry ? <strong className="series-list-score">{entry.rating ? `${entry.rating}/10` : 'Без оценки'}</strong> : <button className="add-library-button" onClick={() => setEditing(movie)}>+ В библиотеку</button>}</div></article>})}</section>}
    </div><aside className="series-statistics"><p className="eyebrow">Общая статистика</p><h2>Фильмы</h2><dl><div><dt>Количество фильмов</dt><dd>{movies.length}</dd></div><div><dt>В библиотеке</dt><dd>{Object.keys(library).length}</dd></div><div><dt>Просмотрено</dt><dd>{Object.values(library).filter((entry) => entry.status === 'COMPLETED').length}</dd></div><div><dt>В планах</dt><dd>{Object.values(library).filter((entry) => entry.status === 'PLANNED').length}</dd></div><div><dt>Фильмы</dt><dd>{movies.filter((movie) => movie.format === 'LIVE_ACTION').length}</dd></div><div><dt>Мультфильмы</dt><dd>{movies.filter((movie) => movie.format === 'ANIMATION').length}</dd></div></dl></aside></section>
    {editing && <MovieForm movie={editing === 'new' ? undefined : editing} library={editing === 'new' ? undefined : library[editing.id]} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void load() }} />}
  </div>
}

export function MovieForm({ movie, library, onClose, onSaved }: { movie?: Movie; library?: LibraryEntry; onClose: () => void; onSaved: () => void }) {
  const [film, setFilm] = useState<MovieInput>(movie ? { ...movie } : emptyMovie)
  const [entry, setEntry] = useState<LibraryInput>(library ? { status: library.status === 'COMPLETED' ? 'COMPLETED' : 'PLANNED', rating: library.rating, favorite: library.favorite, startedAt: library.startedAt, completedAt: library.completedAt, personalNote: library.personalNote } : emptyLibrary)
  const [inLibrary, setInLibrary] = useState(Boolean(library) || !movie)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const setFilmValue = <K extends keyof MovieInput>(key: K, value: MovieInput[K]) => setFilm((current) => ({ ...current, [key]: value }))
  const setEntryValue = <K extends keyof LibraryInput>(key: K, value: LibraryInput[K]) => setEntry((current) => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(null); try { const saved = movie ? await updateMovie(movie.id, film) : await createMovie(film); if (inLibrary) await putInLibrary(saved.id, entry); onSaved() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось сохранить фильм') } finally { setSaving(false) } }
  const removeCatalog = async () => { if (!movie || !window.confirm(`Удалить «${movie.title}» из общего каталога вместе со всей историей?`)) return; try { await deleteMovie(movie.id); onSaved() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось удалить фильм') } }
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><form className="habit-form movie-form" onSubmit={(event) => void submit(event)}><div className="form-heading"><div><p className="eyebrow">Фильмы</p><h2>{movie ? 'Редактирование' : 'Новый фильм'}</h2></div><button type="button" onClick={onClose}>×</button></div>{error && <div className="form-error">{error}</div>}<label>Название<input required maxLength={300} value={film.title} onChange={(event) => setFilmValue('title', event.target.value)} /></label><label>Оригинальное название<input maxLength={300} value={film.originalTitle ?? ''} onChange={(event) => setFilmValue('originalTitle', event.target.value || null)} /></label><div className="movie-details-grid"><label>Формат<select value={film.format} onChange={(event) => setFilmValue('format', event.target.value as ContentFormat)}><option value="LIVE_ACTION">Фильм</option><option value="ANIMATION">Мультфильм</option></select></label><label>Год<input min="1888" type="number" value={film.releaseYear ?? ''} onChange={(event) => setFilmValue('releaseYear', event.target.value ? Number(event.target.value) : null)} /></label><label>Длительность, мин<input min="1" type="number" value={film.durationMinutes ?? ''} onChange={(event) => setFilmValue('durationMinutes', event.target.value ? Number(event.target.value) : null)} /></label><label>Жанр<input maxLength={100} value={film.genre ?? ''} onChange={(event) => setFilmValue('genre', event.target.value || null)} /></label></div><label>URL обложки<input type="url" value={film.coverUrl ?? ''} onChange={(event) => setFilmValue('coverUrl', event.target.value || null)} /></label><label>Описание<textarea rows={3} value={film.description ?? ''} onChange={(event) => setFilmValue('description', event.target.value || null)} /></label>
    <fieldset className="library-fields"><legend>Моя библиотека</legend><label className="all-day-check"><input type="checkbox" checked={inLibrary} onChange={(event) => setInLibrary(event.target.checked)} />Добавить в библиотеку</label>{inLibrary && <><div className="form-grid"><label>Статус<select value={entry.status} onChange={(event) => setEntryValue('status', event.target.value as LibraryStatus)}>{movieStatuses.map((value) => <option key={value} value={value}>{statusLabels[value]}</option>)}</select></label><label>Оценка<select value={entry.rating ?? ''} onChange={(event) => setEntryValue('rating', event.target.value ? Number(event.target.value) : null)}><option value="">Без оценки</option>{Array.from({ length: 10 }, (_, index) => index + 1).map((value) => <option key={value}>{value}</option>)}</select></label></div><label className="favorite-check"><input type="checkbox" checked={entry.favorite} onChange={(event) => setEntryValue('favorite', event.target.checked)} />В избранном</label><label>Личная заметка<textarea rows={2} value={entry.personalNote ?? ''} onChange={(event) => setEntryValue('personalNote', event.target.value || null)} /></label></>}</fieldset>
    <div className="form-buttons">{movie && <button className="danger-button" type="button" onClick={() => void removeCatalog()}>Удалить из каталога</button>}<button className="secondary-button" type="button" onClick={onClose}>Отмена</button><button className="primary-button" disabled={saving}>{saving ? 'Сохраняем…' : 'Сохранить'}</button></div></form></div>
}
