import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { createMovie, deleteMovie, getLibrary, getMovies, getMovieWatches, putInLibrary, removeFromLibrary, updateMovie, watchMovie, type ContentFormat, type LibraryEntry, type LibraryInput, type LibraryStatus, type Movie, type MovieInput, type Watch } from '../api/movies'

const statusLabels: Record<LibraryStatus, string> = { PLANNED: 'В планах', IN_PROGRESS: 'Смотрю', COMPLETED: 'Просмотрено', PAUSED: 'На паузе', DROPPED: 'Брошено' }
const movieStatuses: LibraryStatus[] = ['PLANNED', 'COMPLETED']
const emptyMovie: MovieInput = { title: '', originalTitle: null, itemType: 'MOVIE', format: 'LIVE_ACTION', releaseYear: null, description: null, coverUrl: null, durationMinutes: null, releaseStatus: 'RELEASED' }
const emptyLibrary: LibraryInput = { status: 'PLANNED', rating: null, favorite: false, startedAt: null, completedAt: null, personalNote: null }
const formatDuration = (minutes: number | null) => minutes == null ? null : `${Math.floor(minutes / 60)} ч ${minutes % 60} мин`

export function MoviesPage() {
  const [movies, setMovies] = useState<Movie[]>([])
  const [library, setLibrary] = useState<Record<number, LibraryEntry>>({})
  const [watches, setWatches] = useState<Record<number, Watch[]>>({})
  const [editing, setEditing] = useState<Movie | 'new' | null>(null)
  const [historyMovie, setHistoryMovie] = useState<Movie | null>(null)
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState<LibraryStatus | ''>('')
  const [format, setFormat] = useState<ContentFormat | ''>('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const load = useCallback(async () => { setLoading(true); setError(null); try { const [catalog, allLibrary] = await Promise.all([getMovies(), getLibrary()]); const movieLibrary = allLibrary.filter((entry) => entry.content.itemType === 'MOVIE'); setMovies(catalog); setLibrary(Object.fromEntries(movieLibrary.map((entry) => [entry.content.id, entry]))); const pairs = await Promise.all(catalog.map(async (movie) => [movie.id, await getMovieWatches(movie.id)] as const)); setWatches(Object.fromEntries(pairs)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось загрузить фильмы') } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const visible = useMemo(() => { const normalized = query.trim().toLocaleLowerCase('ru-RU'); return movies.filter((movie) => (!normalized || `${movie.title} ${movie.originalTitle ?? ''}`.toLocaleLowerCase('ru-RU').includes(normalized)) && (!format || movie.format === format) && (!status || library[movie.id]?.status === status)) }, [format, library, movies, query, status])
  const addWatch = async (movie: Movie) => { try { await watchMovie(movie.id); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось сохранить просмотр') } }
  const removeLibrary = async (movie: Movie) => { if (!window.confirm(`Убрать «${movie.title}» из вашей библиотеки? История просмотров останется.`)) return; try { await removeFromLibrary(movie.id); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось убрать фильм') } }

  return <div className="movies-page">
    <section className="media-toolbar"><div className="journal-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Найти фильм" /></div><div className="media-filters"><select value={status} onChange={(event) => setStatus(event.target.value as LibraryStatus | '')}><option value="">Все статусы</option>{movieStatuses.map((value) => <option key={value} value={value}>{statusLabels[value]}</option>)}</select><select value={format} onChange={(event) => setFormat(event.target.value as ContentFormat | '')}><option value="">Все форматы</option><option value="LIVE_ACTION">Фильм</option><option value="ANIMATION">Мультфильм</option></select><button className="primary-button" onClick={() => setEditing('new')}>+ Добавить фильм</button></div></section>
    <section className="media-stats"><div><strong>{movies.length}</strong><span>в каталоге</span></div><div><strong>{Object.keys(library).length}</strong><span>в библиотеке</span></div><div><strong>{Object.values(library).filter((entry) => entry.status === 'COMPLETED').length}</strong><span>просмотрено</span></div><div><strong>{Object.values(watches).flat().length}</strong><span>всего просмотров</span></div></section>
    {error && <div className="notice error movies-error"><strong>Ошибка</strong><span>{error}</span></div>}
    {loading ? <div className="loading"><span />Загружаем медиатеку…</div> : visible.length === 0 ? <div className="media-empty"><span>▶</span><h2>Фильмов пока нет</h2><p>Добавьте первый фильм в каталог.</p></div> : <section className="movie-grid">{visible.map((movie) => { const entry = library[movie.id]; const history = watches[movie.id] ?? []; return <article className="movie-card" key={movie.id}><button className="movie-poster" onClick={() => setEditing(movie)} style={movie.coverUrl ? { backgroundImage: `url(${movie.coverUrl})` } : undefined}><span>{movie.title.slice(0, 1)}</span>{entry?.favorite && <i>♥</i>}<em>{movie.format === 'ANIMATION' ? 'Мультфильм' : 'Фильм'}</em></button><div className="movie-info"><div><h3>{movie.title}</h3>{movie.originalTitle && <p>{movie.originalTitle}</p>}</div><div className="movie-meta"><span>{movie.releaseYear ?? '—'}</span>{movie.durationMinutes && <span>{formatDuration(movie.durationMinutes)}</span>}</div>{entry ? <><div className={`media-status ${entry.status.toLowerCase()}`}>{statusLabels[entry.status]}</div>{entry.rating && <div className="movie-rating">★ {entry.rating}/10</div>}<div className="movie-actions"><button onClick={() => void addWatch(movie)}>✓ Просмотрено</button><button onClick={() => setHistoryMovie(movie)} disabled={!history.length}>История ({history.length})</button><button onClick={() => void removeLibrary(movie)}>×</button></div></> : <button className="add-library-button" onClick={() => setEditing(movie)}>+ В библиотеку</button>}</div></article>})}</section>}
    {editing && <MovieForm movie={editing === 'new' ? undefined : editing} library={editing === 'new' ? undefined : library[editing.id]} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void load() }} />}
    {historyMovie && <WatchHistory movie={historyMovie} watches={watches[historyMovie.id] ?? []} onClose={() => setHistoryMovie(null)} />}
  </div>
}

function MovieForm({ movie, library, onClose, onSaved }: { movie?: Movie; library?: LibraryEntry; onClose: () => void; onSaved: () => void }) {
  const [film, setFilm] = useState<MovieInput>(movie ? { ...movie } : emptyMovie)
  const [entry, setEntry] = useState<LibraryInput>(library ? { status: library.status === 'COMPLETED' ? 'COMPLETED' : 'PLANNED', rating: library.rating, favorite: library.favorite, startedAt: library.startedAt, completedAt: library.completedAt, personalNote: library.personalNote } : emptyLibrary)
  const [inLibrary, setInLibrary] = useState(Boolean(library) || !movie)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const setFilmValue = <K extends keyof MovieInput>(key: K, value: MovieInput[K]) => setFilm((current) => ({ ...current, [key]: value }))
  const setEntryValue = <K extends keyof LibraryInput>(key: K, value: LibraryInput[K]) => setEntry((current) => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(null); try { const saved = movie ? await updateMovie(movie.id, film) : await createMovie(film); if (inLibrary) await putInLibrary(saved.id, entry); onSaved() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось сохранить фильм') } finally { setSaving(false) } }
  const removeCatalog = async () => { if (!movie || !window.confirm(`Удалить «${movie.title}» из общего каталога вместе со всей историей?`)) return; try { await deleteMovie(movie.id); onSaved() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось удалить фильм') } }
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><form className="habit-form movie-form" onSubmit={(event) => void submit(event)}><div className="form-heading"><div><p className="eyebrow">Фильмы</p><h2>{movie ? 'Редактирование' : 'Новый фильм'}</h2></div><button type="button" onClick={onClose}>×</button></div>{error && <div className="form-error">{error}</div>}<label>Название<input required maxLength={300} value={film.title} onChange={(event) => setFilmValue('title', event.target.value)} /></label><label>Оригинальное название<input maxLength={300} value={film.originalTitle ?? ''} onChange={(event) => setFilmValue('originalTitle', event.target.value || null)} /></label><div className="movie-details-grid"><label>Формат<select value={film.format} onChange={(event) => setFilmValue('format', event.target.value as ContentFormat)}><option value="LIVE_ACTION">Фильм</option><option value="ANIMATION">Мультфильм</option></select></label><label>Год<input min="1888" type="number" value={film.releaseYear ?? ''} onChange={(event) => setFilmValue('releaseYear', event.target.value ? Number(event.target.value) : null)} /></label><label>Длительность, мин<input min="1" type="number" value={film.durationMinutes ?? ''} onChange={(event) => setFilmValue('durationMinutes', event.target.value ? Number(event.target.value) : null)} /></label></div><label>URL обложки<input type="url" value={film.coverUrl ?? ''} onChange={(event) => setFilmValue('coverUrl', event.target.value || null)} /></label><label>Описание<textarea rows={3} value={film.description ?? ''} onChange={(event) => setFilmValue('description', event.target.value || null)} /></label>
    <fieldset className="library-fields"><legend>Моя библиотека</legend><label className="all-day-check"><input type="checkbox" checked={inLibrary} onChange={(event) => setInLibrary(event.target.checked)} />Добавить в библиотеку</label>{inLibrary && <><div className="form-grid"><label>Статус<select value={entry.status} onChange={(event) => setEntryValue('status', event.target.value as LibraryStatus)}>{movieStatuses.map((value) => <option key={value} value={value}>{statusLabels[value]}</option>)}</select></label><label>Оценка<select value={entry.rating ?? ''} onChange={(event) => setEntryValue('rating', event.target.value ? Number(event.target.value) : null)}><option value="">Без оценки</option>{Array.from({ length: 10 }, (_, index) => index + 1).map((value) => <option key={value}>{value}</option>)}</select></label></div><label className="favorite-check"><input type="checkbox" checked={entry.favorite} onChange={(event) => setEntryValue('favorite', event.target.checked)} />В избранном</label><label>Личная заметка<textarea rows={2} value={entry.personalNote ?? ''} onChange={(event) => setEntryValue('personalNote', event.target.value || null)} /></label></>}</fieldset>
    <div className="form-buttons">{movie && <button className="danger-button" type="button" onClick={() => void removeCatalog()}>Удалить из каталога</button>}<button className="secondary-button" type="button" onClick={onClose}>Отмена</button><button className="primary-button" disabled={saving}>{saving ? 'Сохраняем…' : 'Сохранить'}</button></div></form></div>
}

function WatchHistory({ movie, watches, onClose }: { movie: Movie; watches: Watch[]; onClose: () => void }) { return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className="watch-history"><div className="form-heading"><div><p className="eyebrow">История просмотров</p><h2>{movie.title}</h2></div><button onClick={onClose}>×</button></div>{[...watches].reverse().map((watch) => <div key={watch.id}><span>Просмотр №{watch.watchNumber}</span><strong>{new Intl.DateTimeFormat('ru-RU', { dateStyle: 'long', timeStyle: 'short' }).format(new Date(watch.watchedAt))}</strong></div>)}</section></div> }
