spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${TEST_DB_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_TEST_DB:life_dashboard_test}}
  flyway:
    enabled: true
    clean-disabled: true
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    com.lifedashboard: INFO
    org.hibernate.SQL: WARN
